movie/movieproject/movieapp/urls.py
from . import views
from django.urls import path, include
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.addmovie,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('addi/<int:id>/',views.addi,name='addi')
 ]

movie/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from  django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.TextField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pictures')

    def __str__(self):
        return self.name

movie/movieproject/movieapp/forms.py
from django import forms
from .models import movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movie/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movies=movie.objects.all()
    context={
        'moviess':movies
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    MMovie=movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'MMovie':MMovie})
def addmovie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie1=movie(name=name,desc=desc,year=year,img=img)
        movie1.save()
    return render(request,'add.html')


def update(request,id):
    Movie=movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return  render(request,'edit.html',{'form':form,'Movie':Movie})

def delete(request,id):
    if request.method=='POST':
        movie1=movie.objects.get(id=id)
        movie1.delete()
        return redirect('/')
    return render(request,'delete.html')
def addi(request,id):
    if request.method=='POST':
        movie1=movie.objects.get(id=id)
        movie1.add()
        return redirect('/')
    return render(request,'add.html')

movie/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter your movie name">
  <input type="text" name="desc" placeholder="enter the description">
  <input type="text" name="year" placeholder="enter the year">
  <input type="file" name="img">
  <input type="submit">

</form>
{%  endblock %}

movie/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="color:red">

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    online movie store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie/movieproject/templates/delete.html
<form method="post">
      {% csrf_token %}
     are you want to be delete this movie?
  <input type="submit">
</form>

movie/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="row">
    <div class="col-md-6">
        <img src="{{MMovie.img.url}}" width="300" height="300">
         <h4>   {{   MMovie.name}}</h4>
    </div>
    <div class="col-md-6">
        <h4><u>{{MMovie.name}}</u></h4>
        <h6>{{MMovie.desc}}</h6>
        <h6>{{MMovie.year}}</h6>
<a class="btn btn-warning" href="{% url 'movieapp:update' MMovie.id %}" >update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' MMovie.id %}" >delete</a>

</div>
</div>
</div>

{% endblock %}
</body>
</html>

movie/movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movie/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
 <div class="row">
{% for i in moviess %}

  <div class="col-md-4 ">
   <div class="card" style="width: 18rem ;">
  <img  src="{{i.img.url}}  " alt=" " height="250px" >
  <div class="card-body">
    <h5 class="card-title">{{i.desc}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id  %}" class="btn btn-primary">view details</a>
  </div>
</div>
  </div>
 {% endfor %}
 </div>

</div>



 {% endblock %}